name: 'clima_sp_dbt'
version: '1.0.0'

profile: 'clima_sp_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  clima_sp_dbt:
    example:
      +materialized: view
